image: node

build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf libc6-i386
  script:
    - export GCC_DIR=$HOME/gcc-arm-none-eabi-9-2019-q4-major
    - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
    - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
    - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
    - export PATH=$PATH:$GCC_DIR/bin
    - make all-boards

  artifacts:
    paths:
      - "build/*.bin"
